export { SecretaryDashboard } from './dashboard';
export { SecretaryStudents } from './students';
export { SecretaryFaculty } from './faculty';
export { SecretarySchedules } from './schedules';
export { SecretaryEvents } from './events';
export { SecretaryResearch } from './research';
export { SecretaryDocuments } from './documents';
export { SecretaryReports } from './reports';
export { SecretaryCurriculum } from './curriculum';
