import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
function formatTime(iso) {
    return new Date(iso).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });
}
export function ConflictAlert({ conflicts }) {
    if (conflicts.length === 0)
        return null;
    return (_jsx("div", { role: "alert", className: "rounded-lg border-2 border-amber-300 bg-amber-50 p-4 shadow-sm", children: _jsxs("div", { className: "flex items-start gap-3", children: [_jsx("div", { className: "flex-shrink-0 w-10 h-10 rounded-full bg-amber-100 flex items-center justify-center", children: _jsx("svg", { className: "w-6 h-6 text-amber-600", fill: "none", stroke: "currentColor", viewBox: "0 0 24 24", children: _jsx("path", { strokeLinecap: "round", strokeLinejoin: "round", strokeWidth: 2, d: "M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" }) }) }), _jsxs("div", { className: "flex-1", children: [_jsx("h3", { className: "font-semibold text-amber-900 mb-2", children: "Scheduling Conflict Detected" }), _jsx("p", { className: "text-sm text-amber-800 mb-3", children: "The following conflicts were found. Please adjust the schedule to resolve them:" }), _jsx("ul", { className: "space-y-2", children: conflicts.map((c, idx) => (_jsxs("li", { className: "flex items-start gap-2 text-sm text-amber-900", children: [_jsx("span", { className: "flex-shrink-0 w-5 h-5 rounded-full bg-amber-200 text-amber-800 flex items-center justify-center text-xs font-semibold", children: idx + 1 }), _jsx("div", { className: "flex-1", children: c.reason === 'room' ? (_jsxs("p", { children: ["Room ", _jsx("span", { className: "font-semibold", children: c.room }), " is already booked for", ' ', _jsx("span", { className: "font-semibold", children: c.subject }), _jsxs("span", { className: "block text-xs text-amber-700 mt-0.5", children: [formatTime(c.startTime), " \u2013 ", formatTime(c.endTime)] })] })) : (_jsxs("p", { children: ["Instructor ", _jsx("span", { className: "font-semibold", children: c.instructor }), " is already scheduled for", ' ', _jsx("span", { className: "font-semibold", children: c.subject }), _jsxs("span", { className: "block text-xs text-amber-700 mt-0.5", children: [formatTime(c.startTime), " \u2013 ", formatTime(c.endTime)] })] })) })] }, `${c.scheduleId}-${c.reason}`))) })] })] }) }));
}
